### ISSUE TITLE
Minor query

### ISSUE THREAD

**Issue by neonfrontier** [DFgraphics/CLA#7]
Hello,
Love your work!
Just wanted to ask if this fix is something that can/cannot be implemented: https://www.reddit.com/r/dwarffortress/comments/2g00rd/starter_pack_updated_with_twbt_graphics_updates/ckewjz7/

Also would like to know if you are the person to ask about TWBT support?

Thank you!

**Comment by jecowa** [comment]
It looks like you are wanting the period instead of the floor. If you are using the Lazy Newb Pack, you might try clicking on the "customize" tab in the "graphics" tab and changing the graphics tileset from "CLA" to "Myne". If you don't like the way that one looks, you could try dragging that tilesheet from the Reddit post into your /LNP/tilesets/ folder, and then switching your graphics pack to something else, and then switching back to CLA, and then going into the "customize" tab and switching it to the tilesheet you just installed. 

CLA was designed to work around some graphics problems in Adventure mode. A big reason that this tileset doesn't have TWBT support is that there are issues with using TWBT in Adventure mode at the moment. I think the game crashes if you try to look at the Adventure mode fast travel map while TWBT is enabled. The DFHack people intend on looking into this issue at some point.

**Comment by neonfrontier** [comment]
Alright, thank you very much for that information. :)
As for the tileset I think the issue is that the punctuation is not working well hence that 'fix' that was posted.

**Comment by claireanlage** [comment]
Sorry for the late reply, wasn't on github for a while.
I'm not interested in TWBT support right now, though I think using the second tileset that comes with this pack (Myne.png) as text/map tileset should work perfectly.

As for the issue with punctuation in general, CLA is basically Myne with opaque ground tiles, so if you prefer punctuation, you can just use that. I don't want to maintain another tileset, that's just CLA without opaque ground tiles, but if PeridexisErrant or other "Noob Pack" guys want to maintain a modified version all the time, I don't mind.
